# Generated by Django 3.1.3 on 2023-07-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230530_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='c_w',
            new_name='is_correct',
        ),
    ]
